### ISSUE TITLE
Revive turtlebot urdf demo

### ISSUE THREAD

**Issue by jihoonl** [RobotWebTools/robotwebtools.github.io#38]
Turtlebot URDF demo has been disabled by the issue #36.
Once brown's new server up and running, we can re-enable this.

**Comment by jihoonl** [comment]
@rctoris  What do I need to do to revive turtlebot urdf demo?

**Comment by rctoris** [comment]
We would need to spin up a new EC2 instance since we can only load one robot URDF per roscore. We had free trials during the time we had the three different models up but no longer do.

**Comment by jihoonl** [comment]
Would it be possible to run docker inside EC2? So we can run multiple ROS dockers in one EC2 instance.

**Comment by jihoonl** [comment]
And how do I access resource.robotwebtools.org? turtlebot_description need to be updated.

**Comment by jihoonl** [comment]
Check this out.

https://github.com/jihoonl/dockers/tree/master/turtlebot_web_view

**Comment by rctoris** [comment]
The resources stuff is hosted on our lab's AWS account. I can look into permissions for an external collaborator to the S3 bin otherwise I can push them up if need be. 

Docker looks cool. I'm trying it now on our EC2 instance. It seems there is a live demo there? Why not just link that page on robotwebtools.org?

**Comment by rctoris** [comment]
Seems like the docker instance worked, its running now: http://demo.robotwebtools.org:8888/

**Comment by jihoonl** [comment]
The demo was temporarily hosted for demonstration. I thought it would be nice to move this to more official location like turtlebot.com or robotwebtools.org.  So it can be stably hosted.

**Comment by jihoonl** [comment]
http://demo.robotwebtools.org:8888/ seems to be dead. At the moment. Once it becomes live, I will create a PR to update demo page.


![demo](https://cloud.githubusercontent.com/assets/1556736/7557241/c485ae56-f7c8-11e4-8dc0-b879c7367160.png)

**Comment by rctoris** [comment]
Yes, that means its running. `8888` is the WebSocket server not an HTTP server so no actual web page will be displayed. Point a web page with a roslib client pointed there like the other examples and I think it should work.

**Comment by jihoonl** [comment]
Nice Thanks. It works!

Can you tell me how to update resource.robotwebtools.org? I am getting the following errors.

![resource_error](https://cloud.githubusercontent.com/assets/1556736/7578957/673d305a-f897-11e4-947d-31477e032361.png)

**Comment by rctoris** [comment]
Can you email me a zip folder with the version of the Collada files you want? I'll push them to the server.

**Comment by jihoonl** [comment]
Sent.

**Comment by rctoris** [comment]
All set!

**Comment by jihoonl** [comment]
Thanks!
