### ISSUE TITLE
roslibjs documentation awry

### ISSUE THREAD

**Issue by jrlandau** [RobotWebTools/robotwebtools.github.io#53]
In the Home page for roslibjs documentation (http://robotwebtools.org/jsdoc/roslibjs/current/), several classes (e.g., ActionClient, Pose, Message, and perhaps others) are missing at least part of their description.  There is much information regarding contributors which is probably not intended. 

This is the page reached by following the documentation link on the libraries page of the robotwebtools web site.

**Comment by rctoris** [comment]
Fixed in https://github.com/RobotWebTools/robotwebtools.github.io/commit/f12cd54ebf7e0f74a31efb78b887faa3dbe96801 -- be sure to clear cache when refreshing for new docs
