### ISSUE TITLE
CDN content not using valid SSL certs

### ISSUE THREAD

**Issue by sevenbitbyte** [RobotWebTools/robotwebtools.github.io#58]
The server [https://cdn.robotwebtools.org](https://cdn.robotwebtools.org) does not have a currently valid SSL key. The content appears to be hosted on AWS cloudfront which has great support for string SSL keys, please use it. This is a serious security and privacy problem which could lead to compromises of fielded systems. Also for users who choose to pull down your code from this avenue will encounter CORS complaints and will need to relax their security settings to enable users to load insecure content. This is a major problem.

If you cannot secure your CDN with SSL you should take it down and encourage users to distribute code independently.

@rctoris @jihoonl

**Comment by jihoonl** [comment]
The new cdn server(static.robotwebtools.org) uses valid SSL.
