### ISSUE TITLE
the website seems to be down

### ISSUE THREAD

**Issue by RoboHash** [RobotWebTools/robotwebtools.github.io#62]
I just visited the website of RobotWebTools (robotwebtools.org) ,however,ifound that the website has been down ,I cannot open any page of it.
  The worst problem is that I cannot download some .js files from cdn.robotwebtools.org to backup to loaclhost,such as "ColladaLoader2.js"  "eventemitter2.min.js" . And I don't know where to find them on other space.So,I cannot try the all demos.
  Sorry for that I cannot describe my problems well in English.
  Could you give me a copy of the all files on cdn.robotwebtools.org or fix the website?
  Thank very much !!!

**Comment by jihoonl** [comment]
Here you are 

https://groups.google.com/d/msg/robot-web-tools/PlW1ECoL91Y/1ss6BPp_DAAJ
