### ISSUE TITLE
robotwebtools.org down / inactive?

### ISSUE THREAD

**Issue by gavanderhoorn** [RobotWebTools/robotwebtools.github.io#63]
Not sure whether this is transient, but I can't seem to reach `http://robotwebtools.org` any more.

**Comment by jihoonl** [comment]
Yes, we are moving to the server at the moment. Please stay tuned in mailing list.

https://groups.google.com/d/msg/robot-web-tools/PlW1ECoL91Y/uI80cp3zDAAJ

**Comment by jihoonl** [comment]
robotwebtools.org is working now.

**Comment by gavanderhoorn** [comment]
The urdf demo page still has to be updated? `cdn` links seem to return `404`s at the moment.

Thanks for keeping this online btw, much appreciated.

**Comment by jihoonl** [comment]
cdn and demo will be back sometime this week or next week.

**Comment by dirk-thomas** [comment]
For future readers: cdn.robotwebtools.org is still down

There is a replacement though under static.robotwebtools.org (you need to pass the path to an actual resource), see the announcement in the GoogleGroup https://groups.google.com/forum/#!msg/robot-web-tools/plGsZWwtNv8/1M3QCCV3AgAJ
