### ISSUE TITLE
How do i "launch" this?

### ISSUE THREAD

**Issue by muttistefano** [RobotWebTools/robotwebtools.github.io#72]

**Comment by muttistefano** [comment]
Sorry for the noobish question.
How do i run this?

**Comment by Behery** [comment]
I assume you're talking about the rosbridge_server? If so you need to do:
`roslaunch rosbridge_server rosbridge_websocket.launch`
You can replace websocket by the launch file you need. Also this is probably the wrong repo(?)

**Comment by muttistefano** [comment]
Thanks.
(right,wrong repo)
