### ISSUE TITLE
Broken subpages of repos

### ISSUE THREAD

**Issue by MatthijsBurgh** [RobotWebTools/robotwebtools.github.io#81]
In the past robotwebtools.org/roslibjs would link to the GH-pages of the rolsibjs repo.

This linking isn't working anymore. This is either caused by renaming this repo from robotwebtools.github.io to robotwebtools.org or by adding the `.nojekyll` file.

**Comment by MatthijsBurgh** [comment]
@amacneil I didn't see any reason why this repo was renamed. www.robotwebtools.org works in both situations. It broke the subpages for repos. By changing it back everything is working again.

**Comment by amacneil** [comment]
Thanks, good catch. I only renamed it for consistency so it matched the domain it was being served from. It's weird that the repo name affects the subdirectory serving, I can't find it documented anywhere. Oh well.
