### ISSUE TITLE
Website down; Maintainers, check this issue!

### ISSUE THREAD

**Issue by MatthijsBurgh** [RobotWebTools/robotwebtools.github.io#82]
Hey Maintainers,

The custom domain, robotwebtools.org, doesn't seem to be working. I have no clue whether this domain was registered somewhere and that registration came to an end. Or GitHub registers these custom domains.

In case of the latter, it is just an temporary issue with GitHub, which doesn't require any action from us. Otherwise it does.

**Comment by MatthijsBurgh** [comment]
@RobotWebTools/roslibjs-maintainers @RobotWebTools/active @RobotWebTools/authors @RobotWebTools/members @RobotWebTools/ros2-0

**Comment by MatthijsBurgh** [comment]
@RobotWebTools/roslibjs-maintainers @RobotWebTools/active @RobotWebTools/authors @RobotWebTools/members @RobotWebTools/ros2-0

**Comment by defunctzombie** [comment]
The CNAME is still set correctly: https://github.com/RobotWebTools/robotwebtools.github.io/blob/master/CNAME

However the `dig` on the domain does not return any response:

```
dig robotwebtools.org

; <<>> DiG 9.10.6 <<>> robotwebtools.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 45223
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;robotwebtools.org.             IN      A

;; Query time: 51 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Apr 07 09:06:33 PDT 2023
;; MSG SIZE  rcvd: 46
```

I don't recall who owns this domain.

**Comment by amacneil** [comment]
As far as I can determine, no one in robot web tools github org knows who controls this domain unfortunately.

**Comment by MatthijsBurgh** [comment]
I checked some websites whether this domain was available. One said it was registered with Amazon since 2012.

In a release document of rolsibjs, which I got from @jihoonl. He said I needed to contact @rctoris for uploading CDNs. So maybe @rctoris knows more about the domain.

**Comment by amacneil** [comment]
Ok, I found out that Zebra (previously Fetch Robotics) own the domain. We're looking into it.

**Comment by Bryant-Yang** [comment]
Hope this to be fixed asap. Many docs and articles reference  robotwebtools.org，it's also the js source imported by many pages.

**Comment by CJdev99** [comment]
Currently trying to use a few sources from the website.  It'd be great to have this back up soon. Anywhere else I can find the js sources?

**Comment by MatthijsBurgh** [comment]
The JS docs of the packages can be found in the `gh-pages` branch of their own repository. You can also clone the repositories and generate the docs yourself.

For other users, please do not respond you are hoping for a quick fix. Just plus one of comments above. To prevent polluting this issue.

**Comment by MatthijsBurgh** [comment]
@amacneil any updates so far?

**Comment by amacneil** [comment]
I do not have an update sorry. I asked @rctoris and he said Fetch/Zebra own the domain but the content being hosted was inadvertently deleted.

I have removed the CNAME and I suggest we focus on updating links to https://robotwebtools.github.io/ so that it is not dependent on a third party owned domain name.

The previous CDN content is gone and will need to be recreated. I cannot speak to whether Fetch/Zebra plan to do this. I was not even aware the CDN existed. If someone can point to documentation on what was hosted on the CDN we can evaluate either rebuilding it or using one of the many package hosting services available these days. If you have a package or website that depends on the old CDN, I suggest you assume it is gone for good and make plans accordingly.

**Comment by MatthijsBurgh** [comment]
Only the CDN of Three and some patched loaders of Three were still used in ROS3DJS. I was already working on migrating to supporting a new version of Three.js. Which would already eliminate the use of these last CDNs.

Older versions of the released JS libs and their dependencies was hosted. So there was no dependency on other parties. (I think that was the idea. I wasn't involved at that point.) Though I already migrated away from it, when upgrading. As there enough CDN providers for GitHub nowadays.

The docs of the JS libs, `roslibjs`, `ros3djs` and `ros2djs`, is already hosted via GH pages. So no issues there.

For now only ROS3DJS will be affected by the missing CDN. As the patched Three loaders are gone for now. But I will resolve that in the next few months. For the meantime I will add some comments to make the user aware.

**Comment by amacneil** [comment]
https://robotwebtools.github.io/ domain will be used going forward.
